### PR TITLE
Update start.scss to conform to bootstrap 5.1 instructions

### PR DESCRIPTION
**Pull request by djKianoosh**
Following the instructions here: https://getbootstrap.com/docs/5.1/customize/sass/#variable-defaults 

Moved the functions import first, to avoid $theme-colors "isn't a valid 
CSS value" https://stackoverflow.com/q/68909199/573389

### CODE REVIEW

**Comment by XhmikosR** [comment]
Thanks but this will be fixed in #49

**Comment by djKianoosh** [comment]
Cool that's good to know. That's why I targeted the v5 branch.

**Comment by XhmikosR** [comment]
Actually, wait. If this is targeting the v5 branch it might still be valid. /CC @mdo

**Comment by djKianoosh** [comment]
The key line from the docs is

> Variable overrides must come after our functions are imported, but before the rest of the imports.

which I also added in a comment so it's not missed. That seems to be the difference.

**Pull request closed without merging**
